def gv

pipeline {
    agent any
    tools {
        nodejs "node"
    }
    stages {
        stage("init") {
                steps {
                    script {
                        gv = load "script.groovy"
                    }
                }
            }

        stage("increment version") {
            steps {
                script {
                    dir("app") {
                       gv.increment()
                    }
                }
            }
        }

        stage("Run tests") {
            steps {
                script {
                    dir("app") {
                       gv.runTest()
                    }
                }
            }
        }

        stage("Build and Push docker image") {
            steps {
               script {
                gv.buildPushImage()
             }
           }
        }

        stage("commit version update") {
            steps {
                script {
                    gv.VersionUpdateCommit()
                    }
                }
            }
        }
    }
