pipeline {
    agent any

    tools {
        nodejs "node"
    }

    stages {
        stage('increment version') {
            steps {
                script {
                    dir("app") {
                        sh "npm version minor"

                        def packageJson = readJSON file: 'package.json'
                        def version = packageJson.version

                        env.IMAGE_NAME = "$version-$BUILD_NUMBER"
                    }
                }
            }
        }

        stage('Run tests') {
            steps {
                script {
                    dir("app") {
                        sh "npm install"
                        sh "npm run test"
                    }
                }
            }
        }

        stage('Build and Push docker image to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-credentials', usernameVariable: 'USER', passwordVariable: 'PASS')]){
                    sh "docker build -t app-nodejs:${IMAGE_NAME} ./app"
                    sh "docker tag app-nodejs:${IMAGE_NAME} ${env.USER}/aws-docker:${IMAGE_NAME}"
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                    sh "docker push ${env.USER}/aws-docker:${IMAGE_NAME}"
                }
            }
        }

        stage('commit version update') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'github-PAT', variable: 'TOKEN')]) {
                        sh 'git config --global user.email "jenkins@example.com"'
                        sh 'git config --global user.name "jenkins"'
                        sh 'git status'
                        sh 'git branch'
                        sh 'git config --list'
                        sh 'git remote set-url origin https://${TOKEN}@github.com/kaydisu/nodejs-twn.git'
                        sh 'git add .'
                        sh 'git commit -m "ci: version bump"'
                        sh 'git push origin HEAD:master2'
                    }
                }
            }
        }
    }
}